package br.com.conductor.pier.api.v2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;



/**
 * Parcel of agreement
 **/

@ApiModel(description = "Parcel of agreement")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen")
public class ParcelaAcordoResponse   {
  
  private Long id = null;
  private Long idAcordo = null;
  private Integer numeroParcela = null;
  private BigDecimal valorParcela = null;
  private String vencimentoParcela = null;
  private BigDecimal saldoParcela = null;
  private String nossoNumero = null;
  private Long idBoletoParcela = null;

  
  /**
   * Identification code of the agreement portion
   **/
  public ParcelaAcordoResponse id(Long id) {
    this.id = id;
    return this;
  }
  
  @ApiModelProperty(example = "null", value = "Identification code of the agreement portion")
  @JsonProperty("id")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  
  /**
   * Identification Code of the Agreement (ID)
   **/
  public ParcelaAcordoResponse idAcordo(Long idAcordo) {
    this.idAcordo = idAcordo;
    return this;
  }
  
  @ApiModelProperty(example = "null", value = "Identification Code of the Agreement (ID)")
  @JsonProperty("idAcordo")
  public Long getIdAcordo() {
    return idAcordo;
  }
  public void setIdAcordo(Long idAcordo) {
    this.idAcordo = idAcordo;
  }

  
  /**
   * Plot Number
   **/
  public ParcelaAcordoResponse numeroParcela(Integer numeroParcela) {
    this.numeroParcela = numeroParcela;
    return this;
  }
  
  @ApiModelProperty(example = "null", value = "Plot Number")
  @JsonProperty("numeroParcela")
  public Integer getNumeroParcela() {
    return numeroParcela;
  }
  public void setNumeroParcela(Integer numeroParcela) {
    this.numeroParcela = numeroParcela;
  }

  
  /**
   * Plot amount
   **/
  public ParcelaAcordoResponse valorParcela(BigDecimal valorParcela) {
    this.valorParcela = valorParcela;
    return this;
  }
  
  @ApiModelProperty(example = "null", value = "Plot amount")
  @JsonProperty("valorParcela")
  public BigDecimal getValorParcela() {
    return valorParcela;
  }
  public void setValorParcela(BigDecimal valorParcela) {
    this.valorParcela = valorParcela;
  }

  
  /**
   * Maturity Date
   **/
  public ParcelaAcordoResponse vencimentoParcela(String vencimentoParcela) {
    this.vencimentoParcela = vencimentoParcela;
    return this;
  }
  
  @ApiModelProperty(example = "null", value = "Maturity Date")
  @JsonProperty("vencimentoParcela")
  public String getVencimentoParcela() {
    return vencimentoParcela;
  }
  public void setVencimentoParcela(String vencimentoParcela) {
    this.vencimentoParcela = vencimentoParcela;
  }

  
  /**
   * Portion balance
   **/
  public ParcelaAcordoResponse saldoParcela(BigDecimal saldoParcela) {
    this.saldoParcela = saldoParcela;
    return this;
  }
  
  @ApiModelProperty(example = "null", value = "Portion balance")
  @JsonProperty("saldoParcela")
  public BigDecimal getSaldoParcela() {
    return saldoParcela;
  }
  public void setSaldoParcela(BigDecimal saldoParcela) {
    this.saldoParcela = saldoParcela;
  }

  
  /**
   * Our number generated by parcel
   **/
  public ParcelaAcordoResponse nossoNumero(String nossoNumero) {
    this.nossoNumero = nossoNumero;
    return this;
  }
  
  @ApiModelProperty(example = "null", value = "Our number generated by parcel")
  @JsonProperty("nossoNumero")
  public String getNossoNumero() {
    return nossoNumero;
  }
  public void setNossoNumero(String nossoNumero) {
    this.nossoNumero = nossoNumero;
  }

  
  /**
   * Ticket identification code
   **/
  public ParcelaAcordoResponse idBoletoParcela(Long idBoletoParcela) {
    this.idBoletoParcela = idBoletoParcela;
    return this;
  }
  
  @ApiModelProperty(example = "null", value = "Ticket identification code")
  @JsonProperty("idBoletoParcela")
  public Long getIdBoletoParcela() {
    return idBoletoParcela;
  }
  public void setIdBoletoParcela(Long idBoletoParcela) {
    this.idBoletoParcela = idBoletoParcela;
  }

  

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParcelaAcordoResponse parcelaAcordoResponse = (ParcelaAcordoResponse) o;
    return Objects.equals(this.id, parcelaAcordoResponse.id) &&
        Objects.equals(this.idAcordo, parcelaAcordoResponse.idAcordo) &&
        Objects.equals(this.numeroParcela, parcelaAcordoResponse.numeroParcela) &&
        Objects.equals(this.valorParcela, parcelaAcordoResponse.valorParcela) &&
        Objects.equals(this.vencimentoParcela, parcelaAcordoResponse.vencimentoParcela) &&
        Objects.equals(this.saldoParcela, parcelaAcordoResponse.saldoParcela) &&
        Objects.equals(this.nossoNumero, parcelaAcordoResponse.nossoNumero) &&
        Objects.equals(this.idBoletoParcela, parcelaAcordoResponse.idBoletoParcela);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, idAcordo, numeroParcela, valorParcela, vencimentoParcela, saldoParcela, nossoNumero, idBoletoParcela);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelaAcordoResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idAcordo: ").append(toIndentedString(idAcordo)).append("\n");
    sb.append("    numeroParcela: ").append(toIndentedString(numeroParcela)).append("\n");
    sb.append("    valorParcela: ").append(toIndentedString(valorParcela)).append("\n");
    sb.append("    vencimentoParcela: ").append(toIndentedString(vencimentoParcela)).append("\n");
    sb.append("    saldoParcela: ").append(toIndentedString(saldoParcela)).append("\n");
    sb.append("    nossoNumero: ").append(toIndentedString(nossoNumero)).append("\n");
    sb.append("    idBoletoParcela: ").append(toIndentedString(idBoletoParcela)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

